### ISSUE TITLE
VCCameraStateFront and camera would need to be mirrored

### ISSUE THREAD

**Issue by hisokarage** [jgh-/VideoCore#140] opened 2015-04-30 12:12 UTC
I'm use VideoCore (0.3.1).
When I set cameraState to VCCameraStateFront it toggles to front camera. 
But when i starts flip it, previewView shows me video with strange angle. And then video picture become upside down.

**Comment by jgh-** [comment] 2015-05-26 16:43
Duplicate of #112

**Closed by jgh-** 2015-05-26 16:43 UTC
