### ISSUE TITLE
Play live stream video from Wowza server

### ISSUE THREAD

**Issue by tevghenii** [jgh-/VideoCore#173] opened 2015-07-14 08:01 UTC
Hi

Thank you for a great library. I use it in my current project and setup the video streaming from app to Wowza server in a hour, it was very easy to use the VCSimpleSession class.

Now I am looking for a way to playback live stream from server in app. Can VCSimpleSession do this? Is any example for this?

Thanks

**Comment by RobertSmart** [comment] 2015-08-10 14:55
We are doing something similar. What sort of app are you trying to create? we've had success using javascript with video.js and its hls component.

**Comment by JALsnipe** [comment] 2015-08-10 14:56
Dupe of #36 and #141.

**Comment by tevghenii** [comment] 2015-08-10 14:59
I use VideoCore in iOs app. I found that AVPlayer from AVFoundation plays video via HLS, so use it in my app.

**Closed** 2015-08-10 15:00 UTC

**Comment by bintu1234** [comment] 2015-12-03 12:41
@tevghenii  i am also using using this videocore library but when i am start the rtmp url it is  not playing at server side and my rtmp url is like rtmp//:serverName.tv/servername/username/stream id is this possible in video core can you please help me out

**Comment by MurphyHBrantley** [comment] 2016-06-06 18:39
@tevghenii Hi, I am trying to setup video streaming from iOS app to Wowza servers.  You said you got it up and running in an hour! I'm having a problem connecting to Wowza servers, could you show me an example of how you connected?

This is how I am trying to start RTMP session (I get NetStream.Publish.Denied) error though:

[_session startRtmpSessionWithURL:
    @"rtmp://ec2-xx-xxx-xxx-xx.compute-1.amazonaws.com/MyStr‌​eamName"
    andStreamKey:@"myStream"];

**Comment by Ali-Sher** [comment] 2016-06-23 03:49
I want to Play Recorded Video from ip camera in my app. the video was Recorded at folder of wowza server .but when i run the project and click to play the video its gives Ecception i.e EXC_BAD_ACCESS (code=1, Address 0xc). Please any one can help me to solve the problem.

**Comment by MurphyHBrantley** [comment] 2016-06-23 12:07
@Ali-Sher you can play video from wowza server through a UIWebView, MPMoviePlayerViewController, or AVPlayerViewController, you will need to include more detail for your problem.  That is a very broad error message.
